- name: Crear el grupo sshlogin y el usuario operador
  hosts: all
  become: yes
  tasks:
    - name: Crear el grupo sshlogin
      group:
        name: sshlogin
        state: present

    - name: Crear el usuario operador y agregarlo al grupo sshlogin
      user:
        name: operador
        password: "{{ 'aCR2XNNaYD@F@Q44Qa627Fq8' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        groups: 
          - sshlogin 
          - sudo
        append: yes  # Asegura que no se eliminen otros grupos del usuario

    - name: Verificar si el grupo sshlogin existe
      debug:
        msg: "El grupo sshlogin y el usuario operador fueron creados exitosamente."