- name: Configurar DIR_MODE en /etc/adduser.conf
  hosts: all
  become: yes
  tasks:
    - name: Descomentar y establecer DIR_MODE=0750
      lineinfile:
        path: /etc/adduser.conf
        regexp: '^#?DIR_MODE='
        line: 'DIR_MODE=0750'
        state: present
        backup: yes  # Crea un respaldo del archivo antes de modificarlo