- name: Instalar y configurar RKE2
  hosts: all
  become: yes
  vars:
    kube_config_path: "/root/.kube/config"
    kube_user: "root"

  tasks:
    - name: Actualizar y actualizar los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Descargar e instalar RKE2
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
      args:
        executable: /bin/bash