---
- name: Copiar la plantilla rke2_config.yaml a la ubicación remota
  hosts: all
  become: yes
  tasks:
    - name: Crear el directorio /etc/rancher/rke2 si no existe
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Copiar la plantilla rke2_config.yaml a /etc/rancher/rke2/config.yaml
      template:
        src: ../templates/rke2_config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Habilitar el servicio RKE2
      systemd:
        name: rke2-agent
        enabled: yes

    - name: Iniciar el servicio RKE2
      systemd:
        name: rke2-agent
        state: started